### ISSUE TITLE
does not work with Angular 10 + Ivy

### ISSUE THREAD

**Issue by 62mkv** [willmendesneto/ngx-copy-to-clipboard#28]
**I'm submitting a ...** (check one with "x")

- [x] bug report => search github for a similar issue or PR before submitting
- [ ] feature request

**Current behavior**

**Expected behavior**

as per README

**Reproduction of the problem**

In an Angular 10 project, with Ivy enabled, adding this dependency with `npm i --save`,  then adding `import` declaration into `app.module.ts` and module name into `imports` block of the `@NgModule` leads to this error: 

```
i ｢wdm｣: Failed to compile.

ERROR in node_modules/ngx-copy-to-clipboard/lib/ngx-copy-to-clipboard.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of MiddlewareUiAppModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-copy-to-clipboard) which declares NgxCopyToClipboardModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available
, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class NgxCopyToClipboardModule {
                       ~~~~~~~~~~~~~~~~~~~~~~~~
```

even with `ngcc` being run after installation.

**Comment by willmendesneto** [comment]
Hi @62mkv Thanks for raising this issue. I'll have a look and come back to this issue asap.

**Comment by willmendesneto** [comment]
@62mkv I just updated the project and fixed the issue. Please update your project to use `ngx-copy-to-clipboard@2.3.0` and it should work as expected.
